FROM ubuntu:16.04

ENV LANG C.UTF-8
RUN export LC_ALL=C.UTF-8; \
  apt-get update -qq; \
  apt-get install -y software-properties-common python-software-properties; \
  add-apt-repository -y ppa:ondrej/php; \
  add-apt-repository -y ppa:ondrej/apache2; \
  apt-get update -qq && apt-get install -y -qq \
  apache2 \
  php7.1 \
  php7.1-dev \
  libapache2-mod-php7.1 \
  php7.1-cli \
  php7.1-opcache \
  php7.1-json \
  php7.1-xmlrpc \
  php7.1-curl \
  php7.1-ldap \
  php7.1-bz2 \
  php7.1-cgi \
  php7.1-soap \
  php7.1-common \
  php7.1-mbstring \
  php7.1-gd \
  php7.1-intl \
  php7.1-xml \
  php7.1-mysql \
  php7.1-zip \
  php7.1-bcmath \
  sudo \
  rsync \
  git-core \
  unzip \
  wget \
  mysql-client \
  vim \
  openssh-server; \
  rm -rf /var/lib/apt/lists/*

# Install redis extension
RUN cd /tmp \
  && git clone --branch 4.3.0 https://github.com/phpredis/phpredis \
  && cd phpredis \
  && phpize \
  && ./configure \
  && make \
  && make install \
  && rm -rf /tmp/phpredis

RUN echo "extension=redis.so" > /etc/php/7.1/mods-available/redis.ini
RUN ln -s /etc/php/7.1/mods-available/redis.ini /etc/php/7.1/apache2/conf.d/30-redis.ini
RUN ln -s /etc/php/7.1/mods-available/redis.ini /etc/php/7.1/cli/conf.d/30-redis.ini

RUN a2enmod rewrite; \
  a2enmod headers

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer
RUN php -r "unlink('composer-setup.php');"

RUN wget https://github.com/drush-ops/drush/releases/download/8.2.3/drush.phar -O - -q > /usr/local/bin/drush
RUN chmod +x /usr/local/bin/composer
RUN chmod +x /usr/local/bin/drush

# Prepare Aegir Logs folder.
RUN mkdir /var/log/aegir
RUN echo 'Hello, Cloudrup.' > /var/log/aegir/system.log

COPY config/php.ini /etc/php/7.1/apache2/php.ini
COPY httpd-foreground /usr/local/bin/httpd-foreground
RUN chmod +x /usr/local/bin/httpd-foreground
COPY config/other-vhosts-access-log.conf /etc/apache2/conf-available/other-vhosts-access-log.conf
COPY config/security.conf /etc/apache2/conf-available/security.conf

RUN systemctl enable ssh

WORKDIR /var/www/html
VOLUME /var/www/html

# docker-entrypoint.sh waits for mysql and runs hostmaster install
ENTRYPOINT []
CMD ["httpd-foreground"]
